name: tugas_besar_hospital_pbp
description: Tugas Besar Hospital PBP
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  camera: ^0.10.5+2
  mobile_scanner: ^3.2.0
  image_picker: ^0.8.6
  shake: ^2.2.0
  path_provider: ^2.0.15
  http: ^1.1.0
  pdf: ^3.6.4
  printing: ^5.9.0
  uuid: ^3.0.6
  barcode_widget: ^2.0.4
  responsive_sizer: ^3.2.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/doctorProfilePictures/
